### PR TITLE
Composer Updates

### PR DESCRIPTION
**Pull request by LukeUKFast**
Option to install composer 1 and or composer 2. In line with Ansible changes for Magento Stack Build

### CODE REVIEW

**Review by miff2000 — COMMENTED** [review]
Is it possible to just target the major version (i.e., `1` or `2`) with the install command? If so then we should do that I think. That way it will pull the latest version of each, instead of being pinned at `1.10.20` or `2.0.1`

**Comment by LukeUKFast** [comment]
Not sure if we can specify a major version: 

~]# php /tmp/composer-installer.php --version=2 --filename=composer2 --install-dir=/usr/bin
The defined install version (2) does not match release pattern.

I believe the latest version for 1 is 1.10.21, but there are no major changes: 

https://github.com/composer/composer/releases/tag/1.10.21

We have the same setup for the ansible - no specific way to target the major version :(

**Comment by miff2000** [comment]
> Not sure if we can specify a major version:
> 
> ~]# php /tmp/composer-installer.php --version=2 --filename=composer2 --install-dir=/usr/bin
> The defined install version (2) does not match release pattern.
> 
> I believe the latest version for 1 is 1.10.21, but there are no major changes:
> 
> https://github.com/composer/composer/releases/tag/1.10.21
> 
> We have the same setup for the ansible - no specific way to target the major version :(

Ah that's a shame. Oh well

**Review by miff2000 — APPROVED** [review]
LGTM

**Review by miff2000 — APPROVED** [review]

**Pull request merged**
