### PR TITLE
meltdown

### PR DESCRIPTION
**Pull request by jackosullivan**
Meltdown documentation. Ideally we would want to get this up tonight so that it is ready for the email tomorrow.

This will also likely be updated frequently over the next few days as new patches are released.

### CODE REVIEW

**Comment by jackosullivan** [comment]
will take a look at the fail now, fix and resubmit.

**Review by garryprior — APPROVED** [review]
nice work @jackosullivan

**Comment by garryprior** [comment]
completed the merge, but link still not yet live on docs.ukfast

**Comment by garryprior** [comment]
still not gone live, not sure if something has gone wrong as it doesn't normally take more than about 10 minutes to put a new article live.  Maybe @laf could take a look?

**Comment by leytonreed** [comment]
I can see it's in the search, but 404 on the page. Feels like an error to me.

**Comment by garryprior** [comment]
it's live now @leytonreed , not sure why the delay but there you go
https://docs.ukfast.co.uk/security/meltdown.html

**Comment by laf** [comment]
Looks like travis have changed the IPs they run builds from, I've whitelisted the new ranges and kicked a build off to test.

In the mean time I've deployed the changes manually.

**Comment by laf** [comment]
Test build goes through ok now so this should be resolved for any future PRs to be merged in @garryprior

**Comment by garryprior** [comment]
thanks @laf

**Pull request merged**
