### PR TITLE
Adding DKIM section to mail

### PR DESCRIPTION
**Pull request by thatdamndog**
Adding a doc page for common DKIM issues and solutions 
Added page to index along with a brief description for the mail section and meta content on both pages

### CODE REVIEW

**Comment by garryprior** [comment]
thanks @thatdamndog , will take a look and review before pushing live.

BTW - who are you, internal I presume?? :-)

**Comment by thatdamndog** [comment]
Hi Garry,

It’s me! Now I’ve actually had a few moments to set myself up, expect a lot of these in the near future.

Also raised an issue I think might help: Email should moved higher in the layout #314

Erm..*be moved

Ta
Shaun

**Comment by garryprior** [comment]
@thatdamndog I corrected your table formatting on the mailconfig page - two of your rows were misaligned by one space on the right hand side.  Github is **very** unforgiving!  this works now

**Comment by garryprior** [comment]
PS:  i still haven't had chance to review though sorry, will get to it next week.

**Comment by thatdamndog** [comment]
No worries, but sooner this is in the hands of engineers and users, the easier our lives get.

**Comment by garryprior** [comment]
will take a look today @thatdamndog .

pls can you start separating these out into separate PRs to make it easier to review and push live

**Comment by thatdamndog** [comment]
I did try, but it's been long enough since using git I've not quite figured it out. 

I'm guessing I'd need to make another branch as you can't have two pull requests on the same branch?

**Comment by garryprior** [comment]
reviewed all files, thanks @thatdamndog - a lot of work went in here!  just waiting for final travis checks then will push live.

**Review by garryprior — APPROVED** [review]

**Comment by garryprior** [comment]
pages are live, I came across a few broken links but have submitted PRs to fix those - @nformby will push these live in the morning.

**Pull request merged**
