### PR TITLE
No <sup> for inline code

### PR DESCRIPTION
**Pull request by jamesdeluk**

### CODE REVIEW

**Review by miff2000 — DISMISSED** [review]

**Comment by miff2000** [comment]
Looks like there are a few spelling issues after updating the file @jamesdeluk. Would you mind taking a look at those?

**Comment by jamesdeluk** [comment]
Can we add some exclusions?

Mispelled words | Solution
--- | ----
uk | from .co.uk
ukfast | UKFast (already properly capitalised)
prover | Corrected to provider
realip | Configuration/technical term
remoteip | Configuration/technical term
rpaf | Configuration/technical term
forwardfor | Configuration/technical term

**Review by miff2000 — APPROVED** [review]
Changes look good to me

**Comment by miff2000** [comment]
I've merged this in as-is @jamesdeluk. Thanks for your contribution!

**Pull request merged**
