### PR TITLE
Add new timeout docs

### PR DESCRIPTION
**Pull request by rbibby**

### CODE REVIEW

**Review by bluemorbo — APPROVED** [review]

**Review by bluemorbo — APPROVED** [review]
LGTM

@miff2000 could you do the honours?

**Comment by miff2000** [comment]
There's a few mentions of the "UKFast defaults". Do we publish what those are anywhere, and could we link to them in these docs?

**Comment by rbibby** [comment]
> There's a few mentions of the "UKFast defaults". Do we publish what those are anywhere, and could we link to them in these docs?

There's a list of them in GitLab but they could change in the future

**Comment by miff2000** [comment]
> > There's a few mentions of the "UKFast defaults". Do we publish what those are anywhere, and could we link to them in these docs?
> 
> There's a list of them in GitLab but they could change in the future

Could we surface those to a customer somehow? If they don't know what the defaults are, the will almost certainly be questions on what they are, resulting in calls and tickets to Support. We are keeping the docs up-to-date in terms of features and how they work, so I think it's only right that defaults (which customers can't otherwise see) be in there too

**Comment by rbibby** [comment]
Updated the PR to mention current defaults @miff2000

**Review by miff2000 — APPROVED** [review]
Awesome, thanks @rbibby!

**Pull request merged**
