### PR TITLE
Move UAT builds/deployments to Github Actions

### PR DESCRIPTION
**Pull request by Xiol**
Moving UAT build and deployments to GitHub Actions and a standalone k3s node.

### CODE REVIEW

**Comment by Xiol** [comment]
Issues with the teardown job, will need to fix that before this is merged.

https://github.com/ukfast/docs.ukfast.co.uk/runs/4489050870?check_suite_focus=true

**Comment by Xiol** [comment]
Merged in @TomCouser's replica changes and fixed the PR number not always appearing in the workflow. Need Tom to check k8s behaviour is expected, then we'll be good to merge.

**Comment by Xiol** [comment]
Also teardown job _should_ be fixed, too.

**Review by miff2000 — APPROVED** [review]
LGTM

**Pull request merged**
