### PR TITLE
Consolidated the two FW sections + improvements

### PR DESCRIPTION
**Pull request by thatdamndog**
- Put the two firewall sections (security/FW and network/FW) into one section. I can understand FW management applies to both network and security, but it makes more sense to have all FW content under network than split acoss two sections. 
- Some content, layout and style tweaks + spelling checks. 
- Added in meta data for all FW pages

### CODE REVIEW

**Comment by garryprior** [comment]
@thatdamndog please could you take a look at the supportedvpns document - it contains references to very old versions of Windows (7, XP).  presumably later versions are also supported?

**Comment by garryprior** [comment]
@laf please could you take a look at this PR, something appears to have broken with the Sphinx build I think?

```
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 482, in send
    raise RetryError(e, request=request)
RetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/d8/34/42232f561662c6b0dcb5c7c4571443cd4f23a2770833cd458486d6b6182c/Sphinx-1.6.6-py2.py3-none-any.whl (Caused by ResponseError('too many 503 error responses',))
The command "pip install Sphinx===1.6.6" failed and exited with 2 during .
```

**Comment by ghost** [comment]
Just looks like it was getting 503's from 'files.pythonhosted.org', just curl'd it now and looks to be getting 200 responses, maybe run the build again?

**Comment by garryprior** [comment]
thanks @BenWUKFast, will give it a try

**Comment by garryprior** [comment]
still failing, same message as above.  any ideas @BenWUKFast ?

**Comment by garryprior** [comment]
I can't see any obvious errors in the changes I've made to the docs themselves

**Comment by garryprior** [comment]
seems to pass Travis now, did anyone fix this or was it a random glitch that corrected itself??

**Review by garryprior — APPROVED** [review]

**Comment by ghost** [comment]
@garryprior Pretty confident it was just a 503 from the python site, not ideal but looks like they've corrected it

**Pull request merged**
