### PR TITLE
Added eCloud Flex Linux Access Instance Information

### PR DESCRIPTION
**Pull request by ThomasUKFast**
Added information for clients to determine how to access their Linux Instances on eCloud Flex with the use of key pair imports, generated through PuTTY.

### CODE REVIEW

**Comment by garryprior** [comment]
@ThomasUKFast this looks great, thanks.  I have just made some minor tweaks.

Do you think it fits better under the Instances category though, maybe move it here https://docs.ukfast.co.uk/cloud/flex/nova/ 

I'd also like someone else to review from a tech perspective if that's OK - maybe @sam-metcalfe @thatdamndog or @BenWUKFast could pick this up?

I am on leave all of next week so if no-one can review it till then, @nformby has the ability to push this live.

**Comment by ghost** [comment]
Had a read over. Looks good to me. Opened #335 for further improvement but that can get its own PR if needed.

**Review by sam-metcalfe — CHANGES_REQUESTED** [review]
source/cloud/flex/general/accesslinuxinstances.md:3 "...provide an SSH [key] in order" "...steps to generate an SSH key [pair] in PuTTY..."

Need to decide if you're capitalising Public Key, peblic Key or Public key, e.g. source/cloud/flex/general/accesslinuxinstances.md:17

Neither are biggies and Garry's already gonna merge so maybe just pick the above up in sep PR.

**Comment by garryprior** [comment]
OK I will push the original version live for now, you guys can pick up #335 in due course

**Comment by garryprior** [comment]
ok made those changes @sam-metcalfe

**Review by sam-metcalfe — APPROVED** [review]

**Comment by ThomasUKFast** [comment]
Let me know when this is live, currently have a client awaiting the documentation.

**Review by garryprior — APPROVED** [review]

**Comment by garryprior** [comment]
pushed, will be live in ~5 minutes

**Comment by garryprior** [comment]
its live
https://docs.ukfast.co.uk/cloud/flex/general/accesslinuxinstances.html

**Pull request merged**
