### PR TITLE
New FASTdesk documentation

### PR DESCRIPTION
**Pull request by benwoolnough**
I have included a new FASTdesk getting started guide which replaces the old getting started guide. This contains text and screenshots relevant to the new FASTdesk platform and is a basic guide on how a user can login.

### CODE REVIEW

**Comment by CountBacula** [comment]
@benwoolnough - I have asked for internal tech review of this before I do the PR review.

**Review by CountBacula — CHANGES_REQUESTED** [review]
You'll need to merge in recent changes from ukfast:master to your own branch benwoolnough:master before this will build. Let me know if you need help with this.

In addition to the above, there are some more straightforward build problems that you'll need to address:

- source/desktop/fastdesk/getting_started/FASTdeskGettingStartedGuide.md: Does not contain meta info
- source/desktop/fastdesk/getting_started/install_citrix_receiver.md : Is not a file or does not exist anymore.
- source/desktop/fastdesk/getting_started/navigatingthestartmenu.md : Is not a file or does not exist anymore.
- source/desktop/fastdesk/getting_started/navigation.md : Is not a file or does not exist anymore.

**Comment by laf** [comment]
@benwoolnough Any update on this one?

**Comment by benwoolnough** [comment]
@laf, Going to work through this with @CountBacula tomorrow

**Review by CountBacula — APPROVED** [review]

**Pull request merged**
