### PR TITLE
Update buying.md

### PR DESCRIPTION
**Pull request by sam-metcalfe**
Update to reflect DCV process changes as per Issue #281.

### CODE REVIEW

**Comment by sam-metcalfe** [comment]
Bah, forgot meta - fixed

**Review by garryprior — APPROVED** [review]

**Comment by garryprior** [comment]
for some reason the changes haven't been reflected yet on the live site.  Sometimes this happens, if it's still not updated by the morning I will look in more detail

**Comment by garryprior** [comment]
checked this morning - changes now live.  I managed to break a link, will fix it this morning.

**Comment by garryprior** [comment]
all fixed

**Pull request merged**
