### PR TITLE
update from Natalie

### PR DESCRIPTION
**Pull request by craiglawson**
Review WAF material

### CODE REVIEW

**Comment by zyio** [comment]
Failing tests for the following reasons. Haven't fixed myself as I'm not sure if you're still adding to this PR.

* `AntiDDoS/index` is missing from the root `index.rst` file
* `Web Application Firewall/index` is missing from the root `index.rst` file. Best to rename to `WebApplicationFirewall`, spaces wind the build method up sometimes.
* `fastdrive/Security Information.md` isn't in the fastdrive `index.rst`. Same recommendation re: spaces.
* `AntiDDoS/Getting_Started` `AntiDDoS/Monitoring_Reports` and `AntiDDoS/Under_attack` don't have valid titles.

**Comment by garryprior** [comment]
still work in progress

Am creating a new Security category to move DDOS, WAF etc. underneath.  May need some help moving stuff around though will try through Gitkraken first!

**Comment by zyio** [comment]
Cool, let me know when this is feature complete, I'll wander over and we can go through the fixes if you want?

**Comment by garryprior** [comment]
well I'm well and truly lost now!  Might need some help @zyio ...

Trying to:

create a new Security category
move WAF, and Anti Virus into this category. publish WAF to live at same time
move Anti DDOS into Security category, but this isn't ready to publish yet.
Also publish a new page called techinformation in FASTdrive category

But I've got a bit muddled up between different repos, and Gitkraken / Github :-(

give me a shout when you're free and hopefully we can figure it out!

**Pull request closed without merging**
