### PR TITLE
eCloud Flex docs restructure

### PR DESCRIPTION
**Pull request by will-marley**
Got a bit fed up of the file hierarchy of the eCloud Flex docs, so re-structured it into new categories and recreated a lot of the index files to match the new layout. Fixed some old documentation that either doesn't work or is deprecated. Also spent some time fixing broken references / URLs in various docs. Made a few new docs along the way. All pages should now have meta too.

### CODE REVIEW

**Comment by will-marley** [comment]
Finally managed to get all the tests passed. Ready for review.

**Comment by will-marley** [comment]
@CountBacula Would you (or other TL) be able to review this when possible?

**Comment by will-marley** [comment]
@miff2000 Repaired all the formatting errors that were obvious immediately, I'll have a proper dig once live if there's anything remaining.

**Comment by miff2000** [comment]
Just looking at the Travis build output for it:
- https://travis-ci.org/ukfast/docs.ukfast.co.uk/builds/577860152

Lines 303 -> 323 seem to indicate some errors that need correcting, if you could have a look at those first?

**Comment by will-marley** [comment]
Fixed the meta errors, the other `Is not a file or does not exist anymore` errors are for files that don't exist **and** shouldn't exist in the restructure.

**Review by miff2000 — APPROVED** [review]
I think this looks fine. The `tests.sh` script is checking for non-existent files, so those errors can probably be ignored

**Comment by miff2000** [comment]
@will-marley this is now live 🙂
- https://docs.ukfast.co.uk/cloud/flex/

**Pull request merged**
