### PR TITLE
Adding documentation for the new ALIAS record.

### PR DESCRIPTION
**Pull request by ledzepp4eva**
Please review this carefully to ensure there isn't anything that doesn't make any sense or any strange formatting issues.

### CODE REVIEW

**Comment by miff2000** [comment]
Check the [Checks](https://github.com/ukfast/docs.ukfast.co.uk/pull/778/checks) tab @ledzepp4eva. A couple of linting issues

**Comment by ledzepp4eva** [comment]
Checks have now been resolved.

**Review by miff2000 — APPROVED** [review]
Looks great 👍 Cheers @ledzepp4eva

**Comment by ledzepp4eva** [comment]
Cheers for the extra formatting :)

**Pull request merged**
