### PR TITLE
Moved metadata to the end, so that it doesn't interfere with search results

### PR DESCRIPTION
**Pull request by miff2000**

### CODE REVIEW

**Comment by garryprior** [comment]
@laf @darrentayloruk do you know if putting meta data at the end of the file is acceptable?  @miff2000 has discovered that putting at or near the top of the file interferes with how search results are displayed on docs.ukfast

**Comment by darrentayloruk** [comment]
Shouldn't matter as long as it works?

Did we get any further with getting the meta right.. saw some comments and asked a q but not h eard anything since..
https://github.com/ukfast/docs.ukfast.co.uk/pull/197

**Comment by miff2000** [comment]
It's passed Travis checks at least...  
How do we check the meta is working? I have this block in my article
```
```eval_rst
.. meta::
    :title: Multi-Protocol VPN Server using SoftEther | UKFast Documentation
    :description: Detailed guidance on setting up a multi-protocol VPN server using SoftEther

```
And the HTML output looks like this when the page is rendered:
```
<meta content="Multi-Protocol VPN Server using SoftEther | UKFast Documentation" name="title" />  
<meta content="Detailed guidance on setting up a multi-protocol VPN server using SoftEther" name="description" />  
```

The search is not finding this article using the keyword `guidance` however

**Comment by miff2000** [comment]
The ideal tag for us to be using and searching upon would be `keywords` wouldn't it?
```
.. meta::
    :keywords: ipsec, vpn, site-to-site, flex, openstack, cisco, asa, sstp, multi-protocol, softether
```

```
<meta name="keywords" content="ipsec,vpn,site-to-site,flex,openstack,cisco,asa,sstp,multi-protocol,softether">
```

**Comment by miff2000** [comment]
I've added some comments to that thread in case you've got seen them

**Comment by garryprior** [comment]
> do you know if putting meta data at the end of the file is acceptable? 

My original questions was more about whether putting meta content at the end of the file works in terms of the page being indexed properly by Google and other search engines.  Clearly we do want on-site search to work, but fundamentally we have to get the site and all pages properly indexed by the main search engines.  Who can provide guidance on this?

**Comment by darrentayloruk** [comment]
If the page builds with meta block at the end, and the final outputted live page has the meta in the right places then this question is answered :) all is good.

the keywords tag is believed to be not as important for search engines anymore, did get a bit spammy, but there is no harm in populating it exactly as @miff2000 has suggested. 

If that assists in the on-site searching then who knows.. can but try and see! 

The other thread is about getting the right meta title tag set, which will def help searching and users, and generally make the site pages better forcing us to think about them :)

**Pull request closed without merging**
