### PR TITLE
FastNetMon Upload

### PR DESCRIPTION
**Pull request by highamjack**
FastNetMon Upload

### CODE REVIEW

**Review by CountBacula — DISMISSED** [review]
FastNetMon requires .md extension and should be all lower case. Will then re-view for typos etc.

**Comment by miff2000** [comment]
I've cleaned up the history and added the `FastNetMon` word to the `.wordlist.txt` file. Should be good to review now @CountBacula

**Review by miff2000 — APPROVED** [review]
LGTM

**Comment by miff2000** [comment]
@CountBacula I've reworded some of this. Please can you review to make sure you're happy?

**Pull request merged**
