### PR TITLE
this is adding a docs page for ddosx ips

### PR DESCRIPTION
**Pull request by ledzepp4eva**
this is place that references all out IP ranges so clients know it.

### CODE REVIEW

**Comment by ledzepp4eva** [comment]
now this pull request is all i want to merge as i'm still working on cdn troubleshooting stuff.

**Comment by garryprior** [comment]
@ledzepp4eva You need to add meta data to every new or edited page now.  this is so we can get docs.ukfast properly indexed by search engines.

Please add this to the top of the file, above the # H1 page title 

```
```eval_rst
.. meta::
   :title: IP ranges on DDoSX\ :sup:`®` | UKFast Documentation 
   :description: A list of IPv4 and IPv6 ranges used by the DDoSX\ :sup:`®` network
```

**Comment by garryprior** [comment]
this seems to have stalled @ledzepp4eva ?

**Comment by garryprior** [comment]
I made a couple of tweaks @ledzepp4eva , hopefully this should go through now

**Comment by garryprior** [comment]
worked...want me to push this live now?

**Comment by ledzepp4eva** [comment]
I'm happy with it, so feel free @garryprior  (:

**Review by garryprior — APPROVED** [review]

**Pull request merged**
