### PR TITLE
Adding BCP initial docs

### PR DESCRIPTION
**Pull request by leytonreed**
Written up some documentation on BCP / Linux clusters today, should be a good start.

### CODE REVIEW

**Comment by leytonreed** [comment]
@laf @garryprior - Would you mind having a look over this for merging?

**Comment by garryprior** [comment]
Hey @leytonreed , thanks for writing this up, looks very comprehensive.  I think BCP fits best under the Backups and Disaster Recovery category rather than being a top level category.  Please could you move it under source/backups/ and then I'll merge.

**Comment by leytonreed** [comment]
@garryprior - I'd be inclined to disagree, as it's not really a platform for "DR" in the traditional sense *(what is my plan if the office catches on fire?)*, but more for "HA".

If not destined to be a top-level item here, then perhaps it would be better suited to being moved to be with our Load Balancer documentation - but the placement of this under "Networking" seems a little suspect for both of these products.

Perhaps a new category for "High Availability" would make more sense? Or renaming the backups category to "Backups, DR and HA"?

It's your website though, so if you want it to go under "Backups and DR", I'll move it over :smile:

**Comment by garryprior** [comment]
lets go with renaming the the Backups category - I will change to "Backup, DR, and High Availability"

**Comment by garryprior** [comment]
PS:  most other cloud providers put Load Balancers under their Networking category - interested in why you think this doesn't make sense?

**Comment by leytonreed** [comment]
@garryprior - No problem, I'll move things around for you if you'd like and add it in here?

In terms of the LB - yes, it is a networking device, but used to facilitate HA. Given that we're selling multiple HA-style solutions, I'd look there first as a client rather than in the networking section.

Plus when you consider the L7 capabilities of newer LBs, they're less of a networking device per-say.

Not that it's inappropriate, just would make sense to group things in a way that clients can easily hop between relevant docs. Perhaps I could put a redirect in place from `networking/lb` to `ha/lb`, effectively?

**Comment by garryprior** [comment]
@leytonreed yes please if you could move the BCP section that would be great.  Pls could you amend the heading of /source/backups/index.rst to "Backup, DR, and High Availability" at the same time, this will feed through to the top level category name on the homepage and menu.

thanks for the comments - it's always difficult to find an appropriate grouping...at the end of the day so much of what we do goes together; there are always arguments for grouping things differently.

**Comment by leytonreed** [comment]
@garryprior - All done, I've checked and can't see any dead links - I've also correct some of the already-dead links in the FASTCloudBackup pages, so those should now be working.

**Pull request merged**
