### PR TITLE
Added Flavour Sizing Information

### PR DESCRIPTION
**Pull request by ThomasUKFast**
Added more detailed information on individual flavour sizing for instances in eCloud Flex.

### CODE REVIEW

**Comment by garryprior** [comment]
@ThomasUKFast this should sit under the Nova (eCloud Flex Instances) category here https://docs.ukfast.co.uk/cloud/flex/nova/#

On the table itself please add a column called Flavour Type, and list as below in this order:

- Small
- General Purpose (std instances)
- High Memory (mem)
- High IO (io)
- High CPU (cpu)

**Comment by ThomasUKFast** [comment]
@garryprior completed, let me know if any further changes needed.

**Review by garryprior — APPROVED** [review]

**Comment by ThomasUKFast** [comment]
@garryprior Looks like the table markdown format isn't valid? It is valid markdown, so unsure why this is not displaying correctly.

https://docs.ukfast.co.uk/cloud/flex/nova/flavour_sizes.html

**Comment by garryprior** [comment]
need to put the table in RST format, check this page for example - https://github.com/ukfast/docs.ukfast.co.uk/blob/master/source/cloud/flex/nova/newinstances.md

**Comment by garryprior** [comment]
this should do the trick


```eval_rst
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| Flavour Type    | Flavour        | Disk Size (GB) | vCPUs | Memory (GB) | IOPS | Network (Mbps) |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| Small           | UKF2-small-1x0 | 20             | 1     | 0.5         | 500  | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| Small           | UKF2-small-1x1 | 20             | 1     | 1           | 1000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| General Purpose | UKF2-std-2x2   | 60             | 2     | 2           | 1000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| General Purpose | UKF2-std-4x4   | 60             | 4     | 4           | 1000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| General Purpose | UKF2-std-8x8   | 60             | 8     | 8           | 1000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High Memory     | UKF2-mem-1x8   | 60             | 1     | 8           | 2500 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High Memory     | UKF2-mem-2x16  | 60             | 2     | 16          | 2500 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High Memory     | UKF2-mem-4x32  | 60             | 4     | 32          | 2500 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High Memory     | UKF2-mem-8x64  | 60             | 8     | 64          | 2500 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High IO         | UKF2-io-1x2    | 60             | 1     | 2           | 5000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High IO         | UKF2-io-2x4    | 60             | 2     | 4           | 5000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High IO         | UKF2-io-4x8    | 60             | 4     | 8           | 5000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High IO         | UKF2-io-8x16   | 60             | 8     | 16          | 5000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High CPU        | UKF2-cpu-2x12  | 60             | 2*    | 12          | 3000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High CPU        | UKF2-cpu-4x24  | 60             | 4*    | 24          | 3000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High CPU        | UKF2-cpu-6x36  | 60             | 6*    | 36          | 3000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
| High CPU        | UKF2-cpu-8x48  | 60             | 8*    | 48          | 3000 | 10,000         |
+-----------------+----------------+----------------+-------+-------------+------+----------------+
```

**Pull request merged**
