### PR TITLE
Change logo and brand colours

### PR DESCRIPTION
**Pull request by rbibby**

### CODE REVIEW

**Comment by rbibby** [comment]
I can't change the footer colours to the new blue palette because the accreditations image has a grey background rather than transparent.

If anyone can get me one with a transparent (or `#132F3F` blue) background I can swap this and the two shades of grey still being used

docs rebrand mismatch

**Comment by rbibby** [comment]
There's a few references to `#E65743` left but I think they're unused, I can't find them on my test copy to check what exactly it is I'm changing.

I think we could get this out as a first version then look through the site again in desktop, tablet and mobile and target any instances left.

**Comment by rbibby** [comment]
@miff2000 This PR covers the rebranding for the logo, the favicon, the header colour and the little edit / back to top side button colours. It also changes the address to `Archway 1` as we did last week in MyUKFast

See comment above (https://github.com/ukfast/docs.ukfast.co.uk/pull/949#issuecomment-1039282925) about the footer colour if you're able to arrange that or know who can?

**Comment by Xiol** [comment]
Deploying to UAT for checks

**Comment by Xiol** [comment]
https://pr-949.docsuat.devops.ukfast.co.uk/

**Comment by rbibby** [comment]
Search is still red on mobile, the logo also doesn't link back to the homepage on mobile but that's an existing issue I think

I'll fix both first thing tomorrow

image

**Comment by rbibby** [comment]
I can't see the red search bar on my copy, there's an issue with the JS dependencies.

I've made the change I think is needed so that's ready to test on UAT again once it's redeployed.

**Comment by Xiol** [comment]
UAT deployment should be up to date now.

**Comment by rbibby** [comment]
The logo still doesn't link to the homepage on mobile but that's an existing issue. I think it's the overlap of the search box, even when it's not focused. I'll create a separate issue for that to keep this moving.

The red on the search box has been fixed so I'm happy for this to be reviewed now.

**Review by miff2000 — APPROVED** [review]
LGTM

**Pull request merged**
