### PR TITLE
Schedule Firewall Reboot page

### PR DESCRIPTION
**Pull request by danHavercroft2**
Adding a page showing how to schedule dedicated firewall reboots in MyUKFast.

### CODE REVIEW

**Comment by danHavercroft2** [comment]
Tried something that didn't work. Asking Garry to have a look at this as I can't work out why it's failing travis

**Comment by garryprior** [comment]
@danHavercroft I can't make sense of the Travis errors but one thing I can see is that you haven't added the the new file to the index.rst file of the section you are adding the page to.  i.e. - https://github.com/ukfast/docs.ukfast.co.uk/blob/master/source/network/firewalls/index.rst

please try this and we'll see what happens when the test re-runs

Also you might have to lose the underscores in the file name, sometimes Git doesn't like special characters in file names

**Comment by garryprior** [comment]
One other thing, please re-do the screenshot without the "black pen" markings to cover the IPs etc.  If we need to obscure sensitive information please blur it out, take a look at this screenshot as an example:
https://github.com/danHavercroft2/docs.ukfast.co.uk/blob/03e8ce9c9cceba933894af3bbbe6df6e7ca378c8/source/security/ddos/files/connect.PNG

this was done using a Chrome add-in called Awesome Screenshot....others are available

**Comment by ghost** [comment]
If you have a windows jumpbox, then firefox developer screenshot tool can select dom elements to screenshot

**Comment by garryprior** [comment]
@danHavercroft2 please save the image as a .png not .jpg

**Review by garryprior — APPROVED** [review]

**Pull request merged**
