### PR TITLE
Updating FastDesk Documentation

### PR DESCRIPTION
**Pull request by Samuel7441**
Added a fair few pages

### CODE REVIEW

**Comment by miff2000** [comment]
There are merge conflicts which need resolving on this. Please could you address those, @Samuel7441?

* <https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github>

**Comment by miff2000** [comment]
Also, I believe the official format of the name is **FASTdesk**, so be sure that all references to it use that format. The spell checker should pick up on it anyway

**Comment by miff2000** [comment]
It's complaining for spaces in the filename. Could you rename this one @Samuel7441 and update the link too? 

* `source/desktop/fastdesk/Howtoguide/files/Logging in.PNG`

Have a quick check for others too, then commit and push your changes again

**Comment by danHavercroft** [comment]
@miff2000 - CI is failing because of the spelling of "FastDesk". Does this need updating on the docs.ukfast repo master branch or the remote branch?

**Comment by danHavercroft** [comment]
@miff2000 Speaking with Sam A, the correct spelling should be FastDesk not FASTdesk

**Comment by miff2000** [comment]
> @miff2000 Speaking with Sam A, the correct spelling should be FastDesk not FASTdesk

Looks like we have it incorrect on a few of our website pages then too

* <https://www.ukfast.co.uk/fastoffice.html>
* <https://www.ukfast.co.uk/product-terms/fastdesk.html>

If you're 100% sure it should be `FastDesk`, please can you do a sweep across the whole repo and update them to `FastDesk`? The dictionary file which has it stored in the `FASTdesk` case will need updating too. It's here:

* <https://github.com/ukfast/docs.ukfast.co.uk/blob/master/.wordlist.txt>

**Review by miff2000 — APPROVED** [review]
LGTM. Thanks for the contribution and time spent, both of you!

**Pull request merged**
