### PR TITLE
Adding metadata

### PR DESCRIPTION
**Pull request by will-marley**
accidentally added this one to a different branch pull

### CODE REVIEW

**Review by will-marley — COMMENTED** [review]
mis-formatted

**Comment by will-marley** [comment]
still didn't like this change - debugging

**Review by will-marley — COMMENTED** [review]
Trying again, mis-formatted somewhere

**Review by will-marley — COMMENTED** [review]
trying again, travis  doesn't like me

**Review by will-marley — COMMENTED** [review]
keep getting travis errors, he'll get there

**Comment by will-marley** [comment]
Don't know what was up with it but it's passed travis now

**Review by garryprior — APPROVED** [review]
you got there eventually, thanks @will-marley 

Travis can be very unforgiving at times!

**Pull request merged**
