### PR TITLE
Adding SPF and various parts

### PR DESCRIPTION
**Pull request by thatdamndog**
Ben has shown me the magic of correct workflow, this pull will be the last messy pull to get all my current work into place. Hopefully I've got my fork up to date so there shouldn't be too many conflicts.  Apologies if it causes any frustration.

Adding in-depth SPF section under mail
Updating existing SPF section under DNS
 - Removed reference to depricated SPF record type
 - Updated wizard link to one that works
 - Added links to new in-depth guide

Adding link to WP security page at Terence's suggestion

### CODE REVIEW

**Comment by garryprior** [comment]
@thatdamndog it's failing Travis checks because the new spf.md file has not been added to an index file anywhere.  where do you want it, presumably in the Linux section's index file?

**Comment by thatdamndog** [comment]
Oops. I'd say until mail index next to DKIM for now.

**Comment by garryprior** [comment]
ok I will add it in when I review the new content

**Comment by garryprior** [comment]
@thatdamndog please could you take another look at the steps to add an SPF record into SafeDNS/MyUKFast in [this article](https://github.com/thatdamndog/docs.ukfast.co.uk/blob/668d0ac527029f51b987f1cc932533ae200c34f4/source/Domains/safedns/spf.md) - I don't think they are up to date having just taken a quick look at MyUKFast.  I think the steps/screenshots need to be updated?

**Comment by garryprior** [comment]
other than that, this PR is ready to go and now passing travis checks.

**Comment by thatdamndog** [comment]
Nix that - I do.

Checking it out now.

**Comment by garryprior** [comment]
let me have a try....I have a domain on there but am not actually using SafeDNS to manage domains

**Comment by garryprior** [comment]
can't figure it out....I'll email you my test account details, you can have a try there.

**Comment by thatdamndog** [comment]
I found mine - turns out I had them all along I just never knew. 

Got screenshots, will update it shortly

**Comment by garryprior** [comment]
ok great

**Review by garryprior — APPROVED** [review]

**Comment by garryprior** [comment]
all done, thanks again @thatdamndog

**Pull request merged**
