### PR TITLE
Exclusion updates based on new backup system

### PR DESCRIPTION
**Pull request by dansjackson**

### CODE REVIEW

**Comment by dansjackson** [comment]
Waiting for fixes branch in PyBacula v2 to be merged before merging this.

**Review by terencesimms — COMMENTED** [review]
LGTM
https://pr-968.docsuat.devops.ukfast.co.uk/dr-ha/ukfast_backup/backup_schedule.html

Just needs approving on monday anew after the pybacula stuff roles out.

**Comment by dansjackson** [comment]
Turns out that Monday is a bank holiday. PyBacula merge is happening Tuesday instead. This needs holding off until Tuesday.

**Review by terencesimms — APPROVED** [review]
LGTM

**Pull request merged**
